name: Build/release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - if: matrix.os == 'ubuntu-latest'
        run: "sudo snap install snapcraft --classic"

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
