name: Build/release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Dist
        run: yarn install && yarn dist

      - name: Upload files
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'dist/*.exe;dist/*.AppImage;dist/*.dmg'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
